export interface IBuildingRecord {
    egid: number,
    street: string,
    street_number: string,
    zip_code: number,
    community:string,
    canton: number,
    major_statistical_region: number,
    community_type: number,
    second_appartement_quota: number,
    tax_burden: number,
    travel_time_to_centers: number,
    public_transport_quality: number,
    noise_exposure: number,
    slope: number,
    exposure: number,
    lake_view: number,
    mountain_view: number,
    distance_to_lakes: number,
    distance_to_rivers: number,
    distance_to_highvoltage_powerlines: number,
    year_of_construction:number,
}